#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Web开发技能 - 快速Web应用构建
"""

import os
from pathlib import Path
from typing import Dict, List, Optional


class WebProjectBuilder:
    """Web项目构建器"""
    
    TEMPLATES = {
        "flask": {
            "files": {
                "app.py": '''from flask import Flask, jsonify, request

app = Flask(__name__)

@app.route('/')
def home():
    return jsonify({"message": "Hello, World!"})

@app.route('/api/health')
def health():
    return jsonify({"status": "ok"})

if __name__ == '__main__':
    app.run(debug=False, port=5000)
''',
                "requirements.txt": '''flask>=2.0.0
flask-cors>=3.0.0
python-dotenv>=1.0.0
''',
                "config.py": '''import os

class Config:
    SECRET_KEY = os.getenv('SECRET_KEY')
    if not SECRET_KEY:
        raise RuntimeError("SECRET_KEY environment variable is required")
    DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'
''',
                ".env.example": '''SECRET_KEY=change-me-to-a-random-string
DEBUG=False
''',
            },
            "dirs": ["static", "templates", "routes", "models"]
        },
        
        "fastapi": {
            "files": {
                "main.py": '''from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

app = FastAPI(title="{name}", version="1.0.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=os.getenv("CORS_ORIGINS", "http://localhost:3000").split(","),
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.get("/")
def read_root():
    return {{"message": "Hello, World!"}}

@app.get("/api/health")
def health_check():
    return {{"status": "ok"}}

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="127.0.0.1", port=8000)
''',
                "requirements.txt": '''fastapi>=0.100.0
uvicorn>=0.23.0
pydantic>=2.0.0
''',
                "models.py": '''from pydantic import BaseModel
from typing import Optional

class Item(BaseModel):
    id: int
    name: str
    description: Optional[str] = None
''',
            },
            "dirs": ["routers", "models", "schemas", "services"]
        },
        
        "express": {
            "files": {
                "package.json": '''{{
  "name": "{name}",
  "version": "1.0.0",
  "description": "Express.js application",
  "main": "server.js",
  "scripts": {{
    "start": "node server.js",
    "dev": "nodemon server.js"
  }},
  "dependencies": {{
    "express": "^4.18.0",
    "cors": "^2.8.5",
    "dotenv": "^16.0.0"
  }},
  "devDependencies": {{
    "nodemon": "^3.0.0"
  }}
}}''',
                "server.js": '''const express = require('express');
const cors = require('cors');
require('dotenv').config();

const app = express();
const PORT = process.env.PORT || 3000;

app.use(cors());
app.use(express.json());

app.get('/', (req, res) => {
    res.json({{ message: 'Hello, World!' }});
}});

app.get('/api/health', (req, res) => {
    res.json({{ status: 'ok' }});
}});

app.listen(PORT, () => {
    console.log(`Server running on port ${{PORT}}`);
}});
''',
                ".env.example": '''PORT=3000
NODE_ENV=development
''',
            },
            "dirs": ["routes", "models", "middleware", "controllers"]
        },
        
        "nextjs": {
            "files": {
                "package.json": '''{{
  "name": "{name}",
  "version": "1.0.0",
  "private": true,
  "scripts": {{
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  }},
  "dependencies": {{
    "next": "^14.0.0",
    "react": "^18.0.0",
    "react-dom": "^18.0.0"
  }}
}}''',
                "app/page.tsx": '''export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-center">
      <h1 className="text-4xl font-bold">Hello, World!</h1>
    </main>
  );
}
''',
                "app/layout.tsx": '''export const metadata = {
  title: '{name}',
  description: 'Generated by AI',
}};

export default function RootLayout({{
  children,
}}: {{
  children: React.ReactNode;
}}) {{
  return (
    <html lang="en">
      <body>{{children}}</body>
    </html>
  );
}}
''',
            },
            "dirs": ["app", "components", "lib", "public", "styles"]
        }
    }
    
    def __init__(self, project_name: str, template: str = "flask"):
        self.project_name = project_name
        self.template = template
        self.base_path = Path(project_name)
    
    def create(self) -> str:
        """创建项目"""
        if self.template not in self.TEMPLATES:
            return f"[错误] 未知模板: {self.template}"
        
        template = self.TEMPLATES[self.template]
        
        # 创建目录
        self.base_path.mkdir(exist_ok=True)
        for dir_name in template["dirs"]:
            (self.base_path / dir_name).mkdir(exist_ok=True)
        
        # 创建文件
        for file_path, content in template["files"].items():
            full_path = self.base_path / file_path
            full_path.parent.mkdir(parents=True, exist_ok=True)
            
            # 替换变量
            content = content.format(name=self.project_name)
            
            with open(full_path, 'w', encoding='utf-8') as f:
                f.write(content)
        
        return f"[成功] 项目已创建: {self.base_path.absolute()}"
    
    def generate_api(self, path: str, methods: List[str] = None) -> str:
        """生成API端点"""
        methods = methods or ["GET"]
        
        if self.template == "flask":
            return self._generate_flask_api(path, methods)
        elif self.template == "fastapi":
            return self._generate_fastapi_api(path, methods)
        elif self.template == "express":
            return self._generate_express_api(path, methods)
        
        return "[错误] 不支持的模板"
    
    def _generate_flask_api(self, path: str, methods: List[str]) -> str:
        """生成Flask API"""
        code = f"\n@app.route('{path}', methods={methods})\n"
        code += f"def {path.replace('/', '_').strip('_')}_handler():\n"
        
        for method in methods:
            method_lower = method.lower()
            if method == "GET":
                code += f"    # GET handler\n"
                code += f"    return jsonify({{'message': 'GET {path}'}})\n"
            elif method == "POST":
                code += f"    # POST handler\n"
                code += f"    data = request.get_json()\n"
                code += f"    return jsonify({{'message': 'POST {path}', 'data': data}})\n"
        
        return code
    
    def _generate_fastapi_api(self, path: str, methods: List[str]) -> str:
        """生成FastAPI"""
        code = ""
        for method in methods:
            method_lower = method.lower()
            func_name = path.replace('/', '_').strip('_') + f"_{method_lower}"
            code += f"\n@app.{method_lower}(\"{path}\")\n"
            code += f"def {func_name}():\n"
            code += f"    return {{'message': '{method} {path}'}}\n"
        return code
    
    def _generate_express_api(self, path: str, methods: List[str]) -> str:
        """生成Express API"""
        code = ""
        for method in methods:
            method_lower = method.lower()
            code += f"\napp.{method_lower}('{path}', (req, res) => {{\n"
            code += f"    res.json({{ message: '{method} {path}' }});\n"
            code += "});\n"
        return code


def create_project(name: str, template: str = "flask") -> str:
    """创建Web项目"""
    builder = WebProjectBuilder(name, template)
    return builder.create()


def generate_api(path: str, methods: List[str] = None, template: str = "flask") -> str:
    """生成API代码"""
    builder = WebProjectBuilder("temp", template)
    return builder.generate_api(path, methods)


if __name__ == "__main__":
    # 测试
    print(create_project("myapp", "flask"))
    print("\n" + "="*60 + "\n")
    print(generate_api("/users", ["GET", "POST"], "flask"))
