#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Godot 引擎 MCP 工具

功能：
- 项目管理（创建、配置、删除）
- 场景编辑（创建、修改、删除）
- 脚本生成（GDScript、C#）
- 资源导入（纹理、模型、音频）
- 导出构建（Windows、Android、Web）
- 项目分析（代码质量、性能）

用法：
    python godot_mcp.py project create <name> [options]   # 创建项目
    python godot_mcp.py project open <path>               # 打开项目
    python godot_mcp.py scene create <name> [options]     # 创建场景
    python godot_mcp.py script generate <prompt>          # 生成脚本
    python godot_mcp.py import <files> [options]          # 导入资源
    python godot_mcp.py export <platform> [options]       # 导出项目
    python godot_mcp.py analyze <path>                    # 分析项目

MCP调用：
    {"tool": "godot_mcp", "action": "project_create", "params": {...}}
"""

import json
import sys
import os
import subprocess
import uuid
import re
from pathlib import Path
from typing import Dict, List, Optional, Any
from dataclasses import dataclass
from datetime import datetime

# ============================================================
# 配置
# ============================================================
AI_PATH = Path("/python")
MCP_PATH = AI_PATH / "MCP"
PROJECTS_PATH = Path("D:/Projects/Godot")
PROJECTS_PATH.mkdir(parents=True, exist_ok=True)

# Godot 路径
GODOT_PATHS = [
    Path("%SOFTWARE_DIR%/GJ/Godot/Godot.exe"),
    Path("%SOFTWARE_DIR%/GJ/Godot4/Godot.exe"),
    Path("%DEVTOOLS_DIR%/游戏/Godot/Godot.exe"),
    Path("C:/Program Files/Godot/Godot.exe"),
]

# 模板配置
PROJECT_TEMPLATES = {
    "2d": {
        "description": "2D 游戏项目",
        "features": ["4.2", "Mobile"],
        "default_scene": "Node2D",
    },
    "3d": {
        "description": "3D 游戏项目",
        "features": ["4.2", "Forward Plus"],
        "default_scene": "Node3D",
    },
    "ui": {
        "description": "UI 应用项目",
        "features": ["4.2", "Canvas Items"],
        "default_scene": "Control",
    },
    "vr": {
        "description": "VR 游戏项目",
        "features": ["4.2", "Forward Plus", "XR"],
        "default_scene": "XROrigin3D",
    },
}

# 导出预设
EXPORT_PRESETS = {
    "windows": {
        "name": "Windows Desktop",
        "extension": ".exe",
    },
    "android": {
        "name": "Android",
        "extension": ".apk",
    },
    "web": {
        "name": "Web",
        "extension": "",
    },
    "linux": {
        "name": "Linux/X11",
        "extension": "",
    },
    "macos": {
        "name": "macOS",
        "extension": ".zip",
    },
}

# ============================================================
# Godot MCP
# ============================================================
class GodotMCP:
    """Godot 引擎 MCP 工具"""
    
    def __init__(self):
        self.godot_path = self._find_godot()
    
    def _find_godot(self) -> Optional[Path]:
        """查找 Godot 可执行文件"""
        for path in GODOT_PATHS:
            if path.exists():
                return path
        return None
    
    def _generate_uid(self) -> str:
        """生成 Godot UID"""
        return str(uuid.uuid4()).replace("-", "")[:13]
    
    def _run_godot(self, args: List[str], cwd: Path = None) -> subprocess.CompletedProcess:
        """运行 Godot 命令"""
        if not self.godot_path:
            raise FileNotFoundError("未找到 Godot 可执行文件")
        
        cmd = [str(self.godot_path), "--headless"] + args
        return subprocess.run(cmd, capture_output=True, text=True, cwd=cwd)
    
    # ============================================================
    # 项目管理
    # ============================================================
    def project_create(self, name: str, template: str = "2d", path: str = None) -> Dict:
        """创建 Godot 项目"""
        try:
            # 确定项目路径
            if path:
                project_path = Path(path) / name
            else:
                project_path = PROJECTS_PATH / name
            
            project_path.mkdir(parents=True, exist_ok=True)
            
            # 获取模板配置
            template_config = PROJECT_TEMPLATES.get(template, PROJECT_TEMPLATES["2d"])
            
            # 创建 project.godot
            features_str = str(template_config['features']).replace("'", '"')
            rendering_method = template_config['features'][1].lower().replace(' ', '_')
            
            project_godot = """; Engine Configuration File
; Godot version: 4.x
; Generated by Godot MCP

[application]
config/name=""" + name + """
config/description=""" + template_config['description'] + """
config/features=PackedStringArray(""" + features_str + """)
config/icon="res://icon.svg"

[rendering]
renderer/rendering_method=""" + rendering_method + """
"""
            
            with open(project_path / "project.godot", "w", encoding="utf-8") as f:
                f.write(project_godot)
            
            # 创建目录结构
            (project_path / "scenes").mkdir(exist_ok=True)
            (project_path / "scripts").mkdir(exist_ok=True)
            (project_path / "assets").mkdir(exist_ok=True)
            (project_path / "assets" / "textures").mkdir(exist_ok=True)
            (project_path / "assets" / "audio").mkdir(exist_ok=True)
            (project_path / "assets" / "fonts").mkdir(exist_ok=True)
            
            # 创建默认场景
            self.scene_create(str(project_path), "MainScene", node_type=template_config["default_scene"])
            
            # 设置主场景
            self._set_main_scene(project_path, "scenes/MainScene.tscn")
            
            return {
                "success": True,
                "project_path": str(project_path),
                "name": name,
                "template": template,
                "description": template_config["description"]
            }
        
        except Exception as e:
            return {"success": False, "error": str(e)}
    
    def _set_main_scene(self, project_path: Path, scene_path: str):
        """设置主场景"""
        project_file = project_path / "project.godot"
        
        with open(project_file, "r", encoding="utf-8") as f:
            content = f.read()
        
        # 添加主场景配置
        if "run/main_scene" not in content:
            content += '\n[run]\nmain_scene="res://' + scene_path + '"\n'
            
            with open(project_file, "w", encoding="utf-8") as f:
                f.write(content)
    
    def project_open(self, path: str) -> Dict:
        """打开 Godot 项目"""
        try:
            project_path = Path(path)
            
            if not (project_path / "project.godot").exists():
                return {"success": False, "error": "不是有效的 Godot 项目"}
            
            # 启动 Godot 编辑器
            if self.godot_path:
                subprocess.Popen([
                    str(self.godot_path),
                    "--editor",
                    "--path", str(project_path)
                ])
                
                return {
                    "success": True,
                    "project_path": str(project_path),
                    "message": "Godot 编辑器已启动"
                }
            else:
                return {"success": False, "error": "未找到 Godot 编辑器"}
        
        except Exception as e:
            return {"success": False, "error": str(e)}
    
    def project_analyze(self, path: str) -> Dict:
        """分析 Godot 项目"""
        try:
            project_path = Path(path)
            
            if not (project_path / "project.godot").exists():
                return {"success": False, "error": "不是有效的 Godot 项目"}
            
            # 统计项目信息
            stats = {
                "scenes": len(list(project_path.rglob("*.tscn"))),
                "scripts_gd": len(list(project_path.rglob("*.gd"))),
                "scripts_cs": len(list(project_path.rglob("*.cs"))),
                "resources": len(list(project_path.rglob("*.tres"))),
                "textures": len(list(project_path.rglob("*.png"))) + len(list(project_path.rglob("*.jpg"))),
                "audio": len(list(project_path.rglob("*.ogg"))) + len(list(project_path.rglob("*.wav"))),
            }
            
            # 读取项目配置
            with open(project_path / "project.godot", "r", encoding="utf-8") as f:
                project_config = f.read()
            
            # 提取项目名称
            name_match = re.search(r'config/name="([^"]+)"', project_config)
            project_name = name_match.group(1) if name_match else "Unknown"
            
            return {
                "success": True,
                "project_name": project_name,
                "project_path": str(project_path),
                "stats": stats,
                "total_files": sum(stats.values())
            }
        
        except Exception as e:
            return {"success": False, "error": str(e)}
    
    # ============================================================
    # 场景管理
    # ============================================================
    def scene_create(self, project_path: str, name: str, node_type: str = "Node2D") -> Dict:
        """创建场景"""
        try:
            project = Path(project_path)
            if not project.exists():
                return {"success": False, "error": "项目路径不存在: " + str(project_path)}
            
            scenes_dir = project / "scenes"
            scenes_dir.mkdir(exist_ok=True)
            scene_path = scenes_dir / (name + ".tscn")
            
            # 生成场景内容
            scene_content = """[gd_scene load_steps=1 format=3 uid="uid://""" + self._generate_uid() + """"]

[node name=""" + name + """ type=""" + node_type + """]
"""
            
            with open(scene_path, "w", encoding="utf-8") as f:
                f.write(scene_content)
            
            return {
                "success": True,
                "scene_path": str(scene_path),
                "name": name,
                "node_type": node_type
            }
        
        except Exception as e:
            return {"success": False, "error": str(e)}
    
    def scene_add_node(self, scene_path: str, node_name: str, node_type: str, parent: str = ".") -> Dict:
        """向场景添加节点"""
        try:
            scene_file = Path(scene_path)
            
            with open(scene_file, "r", encoding="utf-8") as f:
                content = f.read()
            
            # 添加节点
            node_entry = '\n[node name="' + node_name + '" type="' + node_type + '" parent="' + parent + '"]\n'
            
            content += node_entry
            
            with open(scene_file, "w", encoding="utf-8") as f:
                f.write(content)
            
            return {
                "success": True,
                "scene": str(scene_path),
                "node": node_name,
                "type": node_type
            }
        
        except Exception as e:
            return {"success": False, "error": str(e)}
    
    # ============================================================
    # 脚本生成
    # ============================================================
    def script_generate(self, prompt: str, node_type: str = "Node2D", language: str = "gdscript") -> Dict:
        """生成脚本"""
        try:
            if language == "gdscript":
                return self._generate_gdscript(prompt, node_type)
            elif language == "csharp":
                return self._generate_csharp(prompt, node_type)
            else:
                return {"success": False, "error": "不支持的语言: " + language}
        
        except Exception as e:
            return {"success": False, "error": str(e)}
    
    def _generate_gdscript(self, prompt: str, node_type: str) -> Dict:
        """生成 GDScript"""
        script_content = '''extends ''' + node_type + '''

# ''' + prompt + '''
# Generated by Godot MCP

class_name My''' + node_type + '''

# 信号
signal state_changed(new_state)

# 导出变量
@export var speed: float = 100.0
@export var health: int = 100

# 内部变量
var velocity: Vector2 = Vector2.ZERO
var is_active: bool = true

func _ready():
    # 初始化
    print("''' + node_type + ''' 已就绪")
    _initialize()

func _process(delta: float):
    # 每帧更新
    if not is_active:
        return
    _update_logic(delta)

func _physics_process(delta: float):
    # 物理更新
    if not is_active:
        return
    _physics_logic(delta)

func _initialize():
    # 初始化逻辑
    # TODO: 实现初始化
    pass

func _update_logic(delta: float):
    # 更新逻辑
    # TODO: 实现更新
    pass

func _physics_logic(delta: float):
    # 物理逻辑
    # TODO: 实现物理
    move_and_slide()

func take_damage(amount: int):
    # 受到伤害
    health -= amount
    if health <= 0:
        _die()

func _die():
    # 死亡处理
    is_active = false
    queue_free()
'''
        
        return {
            "success": True,
            "language": "gdscript",
            "node_type": node_type,
            "code": script_content,
            "filename": "My" + node_type + ".gd"
        }
    
    def _generate_csharp(self, prompt: str, node_type: str) -> Dict:
        """生成 C#"""
        script_content = '''using Godot;
using System;

// ''' + prompt + '''
// Generated by Godot MCP

public partial class My''' + node_type + ''' : ''' + node_type + '''
{
    // 信号
    [Signal]
    public delegate void StateChangedEventHandler(string newState);
    
    // 导出变量
    [Export]
    public float Speed { get; set; } = 100.0f;
    
    [Export]
    public int Health { get; set; } = 100;
    
    // 内部变量
    private Vector2 _velocity = Vector2.Zero;
    private bool _isActive = true;
    
    public override void _Ready()
    {
        GD.Print("Node 已就绪");
        Initialize();
    }
    
    public override void _Process(double delta)
    {
        if (!_isActive) return;
        UpdateLogic(delta);
    }
    
    public override void _PhysicsProcess(double delta)
    {
        if (!_isActive) return;
        PhysicsLogic(delta);
    }
    
    private void Initialize()
    {
        // TODO: 实现初始化
    }
    
    private void UpdateLogic(double delta)
    {
        // TODO: 实现更新
    }
    
    private void PhysicsLogic(double delta)
    {
        // TODO: 实现物理
        MoveAndSlide();
    }
    
    public void TakeDamage(int amount)
    {
        Health -= amount;
        if (Health <= 0)
        {
            Die();
        }
    }
    
    private void Die()
    {
        _isActive = false;
        QueueFree();
    }
}
'''
        
        return {
            "success": True,
            "language": "csharp",
            "node_type": node_type,
            "code": script_content,
            "filename": "My" + node_type + ".cs"
        }
    
    # ============================================================
    # 资源导入
    # ============================================================
    def import_assets(self, project_path: str, files: List[str], target_dir: str = "assets") -> Dict:
        """导入资源"""
        try:
            project = Path(project_path)
            imported = []
            failed = []
            
            for file_path in files:
                src = Path(file_path)
                if not src.exists():
                    failed.append({"file": file_path, "reason": "文件不存在"})
                    continue
                
                # 确定目标目录
                if src.suffix in ['.png', '.jpg', '.jpeg', '.svg', '.webp']:
                    dst_dir = project / target_dir / "textures"
                elif src.suffix in ['.ogg', '.wav', '.mp3']:
                    dst_dir = project / target_dir / "audio"
                elif src.suffix in ['.ttf', '.otf']:
                    dst_dir = project / target_dir / "fonts"
                elif src.suffix in ['.gltf', '.glb', '.obj', '.fbx']:
                    dst_dir = project / target_dir / "models"
                else:
                    dst_dir = project / target_dir
                
                dst_dir.mkdir(parents=True, exist_ok=True)
                
                # 复制文件
                import shutil
                dst = dst_dir / src.name
                shutil.copy2(src, dst)
                
                imported.append(str(dst))
            
            return {
                "success": True,
                "imported": imported,
                "failed": failed,
                "count": len(imported)
            }
        
        except Exception as e:
            return {"success": False, "error": str(e)}
    
    # ============================================================
    # 导出构建
    # ============================================================
    def export_project(self, project_path: str, platform: str, output_path: str = None) -> Dict:
        """导出项目"""
        try:
            project = Path(project_path)
            
            if not (project / "project.godot").exists():
                return {"success": False, "error": "不是有效的 Godot 项目"}
            
            preset = EXPORT_PRESETS.get(platform)
            if not preset:
                return {"success": False, "error": "不支持的平台: " + platform}
            
            # 确定输出路径
            if not output_path:
                output_path = str(project / "builds" / platform / (project.name + preset['extension']))
            
            output = Path(output_path)
            output.parent.mkdir(parents=True, exist_ok=True)
            
            # 导出
            result = self._run_godot([
                "--export-release", preset["name"], str(output)
            ], cwd=project)
            
            if result.returncode == 0:
                return {
                    "success": True,
                    "platform": platform,
                    "output": str(output),
                    "size": output.stat().st_size if output.exists() else 0
                }
            else:
                return {
                    "success": False,
                    "error": result.stderr or "导出失败",
                    "stdout": result.stdout
                }
        
        except Exception as e:
            return {"success": False, "error": str(e)}

# ============================================================
# MCP 接口
# ============================================================
class MCPInterface:
    """MCP 接口"""
    
    def __init__(self):
        self.godot = GodotMCP()
    
    def handle(self, request: Dict) -> Dict:
        """处理 MCP 请求"""
        action = request.get("action")
        params = request.get("params", {})
        
        if action == "project_create":
            return self.godot.project_create(
                params.get("name"),
                params.get("template", "2d"),
                params.get("path")
            )
        
        elif action == "project_open":
            return self.godot.project_open(params.get("path"))
        
        elif action == "project_analyze":
            return self.godot.project_analyze(params.get("path"))
        
        elif action == "scene_create":
            return self.godot.scene_create(
                params.get("project_path"),
                params.get("name"),
                params.get("node_type", "Node2D")
            )
        
        elif action == "scene_add_node":
            return self.godot.scene_add_node(
                params.get("scene_path"),
                params.get("node_name"),
                params.get("node_type"),
                params.get("parent", ".")
            )
        
        elif action == "script_generate":
            return self.godot.script_generate(
                params.get("prompt"),
                params.get("node_type", "Node2D"),
                params.get("language", "gdscript")
            )
        
        elif action == "import_assets":
            return self.godot.import_assets(
                params.get("project_path"),
                params.get("files", []),
                params.get("target_dir", "assets")
            )
        
        elif action == "export_project":
            return self.godot.export_project(
                params.get("project_path"),
                params.get("platform"),
                params.get("output_path")
            )
        
        else:
            return {"success": False, "error": "未知操作: " + action}

# ============================================================
# 命令行接口
# ============================================================
def main():
    """主函数"""
    if len(sys.argv) < 2:
        print(__doc__)
        return
    
    cmd = sys.argv[1]
    godot = GodotMCP()
    
    if cmd == "project":
        if len(sys.argv) < 3:
            print("用法: godot_mcp.py project <create|open|analyze>")
            return
        
        subcmd = sys.argv[2]
        
        if subcmd == "create":
            if len(sys.argv) < 4:
                print("用法: godot_mcp.py project create <name> [template]")
                return
            
            name = sys.argv[3]
            template = sys.argv[4] if len(sys.argv) > 4 else "2d"
            
            result = godot.project_create(name, template)
            
            if result.get("success"):
                print("项目已创建: " + result['project_path'])
                print("  名称: " + result['name'])
                print("  模板: " + result['template'])
            else:
                print("创建失败: " + result.get('error'))
        
        elif subcmd == "open":
            if len(sys.argv) < 4:
                print("用法: godot_mcp.py project open <path>")
                return
            
            result = godot.project_open(sys.argv[3])
            print(result.get("message") or result.get("error"))
        
        elif subcmd == "analyze":
            if len(sys.argv) < 4:
                print("用法: godot_mcp.py project analyze <path>")
                return
            
            result = godot.project_analyze(sys.argv[3])
            
            if result.get("success"):
                print("项目分析: " + result['project_name'])
                print("=" * 60)
                print("场景: " + str(result['stats']['scenes']))
                print("GDScript: " + str(result['stats']['scripts_gd']))
                print("C#: " + str(result['stats']['scripts_cs']))
                print("资源: " + str(result['stats']['resources']))
                print("纹理: " + str(result['stats']['textures']))
                print("音频: " + str(result['stats']['audio']))
                print("总计: " + str(result['total_files']) + " 个文件")
    
    elif cmd == "scene":
        if len(sys.argv) < 3:
            print("用法: godot_mcp.py scene <create|add_node>")
            return
        
        scene_cmd = sys.argv[2]
        
        if scene_cmd == "create":
            if len(sys.argv) < 5:
                print("用法: godot_mcp.py scene create <project_path> <name> [node_type]")
                return
            
            project_path = sys.argv[3]
            name = sys.argv[4]
            node_type = sys.argv[5] if len(sys.argv) > 5 else "Node2D"
            
            result = godot.scene_create(project_path, name, node_type)
            
            if result.get("success"):
                print("场景已创建: " + result['scene_path'])
            else:
                print("创建失败: " + result.get('error'))
    
    elif cmd == "script":
        if len(sys.argv) < 4:
            print("用法: godot_mcp.py script generate <prompt> [node_type] [language]")
            return
        
        prompt = sys.argv[2]
        node_type = sys.argv[3] if len(sys.argv) > 3 else "Node2D"
        language = sys.argv[4] if len(sys.argv) > 4 else "gdscript"
        
        result = godot.script_generate(prompt, node_type, language)
        
        if result.get("success"):
            print("生成的 " + result['language'] + " 代码:")
            print("=" * 60)
            print(result['code'])
    
    elif cmd == "import_assets":
        if len(sys.argv) < 4:
            print("用法: godot_mcp.py import_assets <project_path> <file1> [file2] ...")
            return
        
        project_path = sys.argv[2]
        files = sys.argv[3:]
        
        result = godot.import_assets(project_path, files)
        
        if result.get("success"):
            print("导入成功: " + str(result['count']) + " 个文件")
            for f in result['imported']:
                print("  - " + f)
        else:
            print("导入失败: " + result.get('error'))
    
    elif cmd == "export":
        if len(sys.argv) < 4:
            print("用法: godot_mcp.py export <project_path> <platform> [output_path]")
            return
        
        project_path = sys.argv[2]
        platform = sys.argv[3]
        output_path = sys.argv[4] if len(sys.argv) > 4 else None
        
        result = godot.export_project(project_path, platform, output_path)
        
        if result.get("success"):
            print("导出成功: " + result['output'])
            print("  平台: " + result['platform'])
            print("  大小: " + str(result['size'] / 1024 / 1024) + " MB")
        else:
            print("导出失败: " + result.get('error'))
    
    elif cmd == "mcp":
        # MCP 服务器模式
        print("Godot MCP 服务器已启动")
        
        mcp = MCPInterface()
        
        import select
        
        while True:
            if select.select([sys.stdin], [], [], 0.1)[0]:
                line = sys.stdin.readline()
                if not line:
                    break
                
                try:
                    request = json.loads(line)
                    response = mcp.handle(request)
                    print(json.dumps(response, ensure_ascii=False))
                    sys.stdout.flush()
                except json.JSONDecodeError:
                    print(json.dumps({"success": False, "error": "无效的JSON"}))
                    sys.stdout.flush()
    
    else:
        print("未知命令: " + cmd)
        print(__doc__)

if __name__ == "__main__":
    main()
